name: gitlab
services:
  app:
    image: gitlab/gitlab-ce:latest
    restart: unless-stopped
    environment:
      EDITOR: /bin/vi
      GITLAB_ALLOW_SHA1_RSA: "false"
      LANG: C.UTF-8
      TERM: xterm
    ports:
      - target: 22
        published: "3022"
        protocol: tcp
      - target: 443
        published: "3443"
        protocol: tcp
      - target: 80
        published: "3080"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/gitlab/config
        target: /etc/gitlab
      - type: bind
        source: /DATA/AppData/gitlab/var/log
        target: /var/log/gitlab
      - type: bind
        source: /DATA/AppData/gitlab/var/opt
        target: /var/opt/gitlab
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: |
      GitLab is a cloud-based project management platform that allows software developers to develop and manage codes collaboratively. The platform can be deployed either on-premise or in the cloud.
      
      GitLab helps developers manage the complete code lifecycle, from the inception of an idea to the deployment of code on production. Primary features of GitLab are Git repository management, code review, issue tracking, activity feeds and audit logs. The software is offered in four different editions: Community Edition, Enterprise Edition, GitLab.com and GitLab.io.
      
      Users can upload their codes in the repository. GitLab also provides a repository mirroring feature that allows users to access a repository located on a different server with the help of the GitLab interface.
      
      The code review feature allows users to evaluate code line-by-line and provide comments. The software additionally provides continuous integration (CI) and continuous delivery (CD) to test, build and deploy codes.
      
      The Enterprise Edition of the software offers automated testing, Git hooks, audit trails and administrator features.
    pt_br: |
      GitLab é uma plataforma de gerenciamento de projetos baseada em nuvem que permite aos desenvolvedores de software desenvolver e gerenciar códigos de forma colaborativa. A plataforma pode ser implantada localmente ou na nuvem.
      
       O GitLab ajuda os desenvolvedores a gerenciar o ciclo de vida completo do código, desde o início de uma ideia até a implantação do código na produção. Os principais recursos do GitLab são gerenciamento de repositório Git, revisão de código, rastreamento de problemas, feeds de atividades e logs de auditoria. O software é oferecido em quatro edições diferentes: Community Edition, Enterprise Edition, GitLab.com e GitLab.io.
      
       Os usuários podem fazer upload de seus códigos no repositório. O GitLab também fornece um recurso de espelhamento de repositório que permite aos usuários acessar um repositório localizado em um servidor diferente com a ajuda da interface do GitLab.
      
       O recurso de revisão de código permite que os usuários avaliem o código linha por linha e forneçam comentários. O software também fornece integração contínua (CI) e entrega contínua (CD) para testar, construir e implantar códigos.
      
       A Enterprise Edition do software oferece testes automatizados, ganchos Git, trilhas de auditoria e recursos de administrador.
  tagline:
    en_us: GitLab is the most comprehensive AI-powered DevSecOps Platform.
    pt_br: GitLab é a plataforma DevSecOps mais abrangente com tecnologia de IA.
  developer: ''
  author: adrianocandrade
  icon: https://raw.githubusercontent.com/adrianocandrade/CasaOS-APPsCloud/master/images/icons/gitlab.png
  thumbnail: https://raw.githubusercontent.com/adrianocandrade/CasaOS-APPsCloud/master/images/icons/gitlab.png
  project_url: https://github.com/adrianocandrade/CasaOS-APPsCloud
  screenshot_link:
    - https://raw.githubusercontent.com/adrianocandrade/CasaOS-APPsCloud/master/images/screenshots/gitlab/screenshot-1.png
    - https://raw.githubusercontent.com/adrianocandrade/CasaOS-APPsCloud/master/images/screenshots/gitlab/screenshot-2.png
    - https://raw.githubusercontent.com/adrianocandrade/CasaOS-APPsCloud/master/images/screenshots/gitlab/screenshot-3.png
    - https://raw.githubusercontent.com/adrianocandrade/CasaOS-APPsCloud/master/images/screenshots/gitlab/screenshot-4.png
  store_app_id: gitlab
  title:
    en_us: GitLab
    pt_br: GitLab
  tips:
    before_install:
      en_us: |
        Attention: Cloudreve username and password are in the cloudreve installation logs, the easiest way to view it would be through the portainer application.
      pt_br: |
        Atenção: Usuário e senha do cloudreve esta nos logs de instalação do mesmo, forma mais facil de visualizar seria pelo aplicação portainer.
  category: Developer
  port_map: '3080'