name: cloudreve
services:
  cloudreve:
    environment:
      PGID: "1000"
      PUID: "1000"
      TERM: xterm
      TZ: America/Sao_Paulo
    image: xavierniu/cloudreve:latest
    network_mode: default
    ports:
      - target: 5212
        published: "5212"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/cloudreve/temp_data
        target: /temp_data
      - type: bind
        source: /DATA/AppData/cloudreve/uploads
        target: /cloudreve/uploads
      - type: bind
        source: /DATA/AppData/cloudreve/config
        target: /cloudreve/config
      - type: bind
        source: /DATA/AppData/cloudreve/cloudreve/db
        target: /cloudreve/db
      - type: bind
        source: /DATA/AppData/cloudreve/avatar
        target: /cloudreve/avatar
      - type: bind
        source: /DATA/AppData/cloudreve/downloads
        target: /downloads
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: Cloudreve can help you instantly create a network disk service that can be used for personal and public use and get a flexible file management experience with support for multiple storage policies, virtual file systems, and more.
    pt_br: Cloudreve pode ajudá-lo a criar instantaneamente um serviço de disco de rede que pode ser usado para uso pessoal e público e obter uma experiência flexível de gerenciamento de arquivos com suporte para múltiplas políticas de armazenamento, sistemas de arquivos virtuais e muito mais.
  tagline:
    en_us: Cloudreve can help you instantly create a network disk service that can be used for personal and public use and get a flexible file management experience with support for multiple storage policies, virtual file systems, and more.
    pt_br: Cloudreve pode ajudá-lo a criar instantaneamente um serviço de disco de rede que pode ser usado para uso pessoal e público e obter uma experiência flexível de gerenciamento de arquivos com suporte para múltiplas políticas de armazenamento, sistemas de arquivos virtuais e muito mais.
  developer: ''
  author: adrianocandrade
  icon: https://raw.githubusercontent.com/adrianocandrade/CasaOS-APPsCloud/master/images/icons/cloudreve.png
  thumbnail: https://raw.githubusercontent.com/adrianocandrade/CasaOS-APPsCloud/master/images/icons/cloudreve.png
  project_url: https://github.com/adrianocandrade/CasaOS-APPsCloud
  store_app_id: cloudreve
  title:
    en_us: Cloudreve
    pt_br: Cloudreve
  category: Cloud
  port_map: '5212'
