name: cloudreve
services:
    cloudreve:
        environment:
            PGID: "1000"
            PUID: "1000"
            TERM: xterm
            TZ: America/Sao_Paulo
        image: xavierniu/cloudreve:latest
        network_mode: default
        ports:
            - target: 5212
              published: "5212"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /DATA/AppData/cloudreve/temp_data
              target: /temp_data
            - type: bind
              source: /DATA/AppData/cloudreve/uploads
              target: /cloudreve/uploads
            - type: bind
              source: /DATA/AppData/cloudreve/config
              target: /cloudreve/config
            - type: bind
              source: /DATA/AppData/cloudreve/cloudreve/db
              target: /cloudreve/cloudreve/db
            - type: bind
              source: /DATA/AppData/cloudreve/avatar
              target: /ccloudreve/avatar
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: Cloudreve can help you instantly create a network disk service that can be used for personal and public use and get a flexible file management experience with support for multiple storage policies, virtual file systems, and more.
  tagline:
    en_us: Cloudreve can help you instantly create a network disk service that can be used for personal and public use and get a flexible file management experience with support for multiple storage policies, virtual file systems, and more.
  developer: ''
  author: adrianocandrade
  icon: https://raw.githubusercontent.com/adrianocandrade/CasaOS-APPsCloud/master/icons/cloudreve.png
  thumbnail: https://raw.githubusercontent.com/adrianocandrade/CasaOS-APPsCloud/master/icons/cloudreve.png
  title:
    en_us: Cloudreve
  category: Cloud
  port_map: '5212'
