name: cloudreve
services:
    cloudreve:
        environment:
            HOME: /root
            PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            PGID: "1000"
            PS1: '$(whoami)@$(hostname):$(pwd)\$ '
            PUID: "1000"
            TERM: xterm
            TZ: American/Sao_Paulo
        image: cloudreve/cloudreve:latest
        depends_on:
          - aria2
        network_mode: default
        ports:
            - target: 5212
              published: "5212"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /DATA/AppData/cloudreve/temp_data
              target: /temp_data
            - type: bind
              source: /DATA/AppData/cloudreve/uploads
              target: /cloudreve/uploads
            - type: bind
              source: /DATA/AppData/cloudreve/conf.ini
              target: /cloudreve/conf.ini
            - type: bind
              source: /DATA/AppData/cloudreve/cloudreve.db
              target: /cloudreve/cloudreve.db
            - type: bind
              source: /DATA/AppData/cloudreve/avatar
              target: /ccloudreve/avatar
    aria2:
      container_name: aria2
      image: p3terx/aria2-pro
      restart: unless-stopped
      environment:
        RPC_SECRET: '0RIHkKpROrd2PRN4bgJs9aXbJ5mhW1Na'
        RPC_PORT: 6800
      volumes:
        - type: bind
          source: /DATA/AppData/cloudreve/aria2/config
          target: /aria2/config
        - type: bind
          source: /DATA/AppData/cloudreve/aria2/temp_data
          target: /data
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: Cloudreve can help you instantly create a network disk service that can be used for personal and public use and get a flexible file management experience with support for multiple storage policies, virtual file systems, and more.
  tagline:
    en_us: Cloudreve can help you instantly create a network disk service that can be used for personal and public use and get a flexible file management experience with support for multiple storage policies, virtual file systems, and more.
  developer: ''
  author: adrianocandrade
  icon: https://raw.githubusercontent.com/adrianocandrade/CasaOS-APPsCloud/master/icons/cloudreve.png
  thumbnail: https://raw.githubusercontent.com/adrianocandrade/CasaOS-APPsCloud/master/icons/cloudreve.png
  title:
    en_us: Cloudreve
  category: Cloud
  port_map: '5212'
