name: filerun
services:
    filerun:
        image: filerun/filerun:8.1
        network_mode: default
        environment:
          FR_DB_HOST: db
          FR_DB_PORT: 3308
          FR_DB_NAME: casaosfilerun
          FR_DB_USER: casaosfilerun
          FR_DB_PASS: casaosfilerun
          APACHE_RUN_USER: www-data
          APACHE_RUN_USER_ID: 33
          APACHE_RUN_GROUP: www-data
          APACHE_RUN_GROUP_ID: 33
        ports:
            - target: 80
              published: "3386"
              protocol: tcp
        restart: unless-stopped
        depends_on:
          - db
        links:
          - db:db
        volumes:
            - type: bind
              source: /DATA/AppData/filerun/html
              target: /var/www/html
            - type: bind
              source: /DATA/AppData/filerun/user-file
              target: /user-files
    db:
      image: mariadb:10.1
      environment:
        MYSQL_ROOT_PASSWORD: casaosfilerun
        MYSQL_USER: casaosfilerun
        MYSQL_PASSWORD: casaosfilerun
        MYSQL_DATABASE: casaosfilerun
      volumes:
        - type: bind
          source: /DATA/AppData/filerun/db
          target: /var/lib/mysql
      ports:
            - target: 3306
              published: "3308"
              protocol: tcp
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: FileRun - Just like you do with an FTP server, point FileRun to where you keep the files on your server, and you will get instant web access to them.
  tagline:
    en_us: FileRun - Just like you do with an FTP server, point FileRun to where you keep the files on your server, and you will get instant web access to them.
  developer: ''
  author: adrianocandrade
  icon: https://raw.githubusercontent.com/adrianocandrade/CasaOS-APPsCloud/master/icons/filerun.png
  thumbnail: https://raw.githubusercontent.com/adrianocandrade/CasaOS-APPsCloud/master/icons/filerun.png
  title:
    en_us: FileRun
  category: Cloud
  port_map: '3386'
