name: filerun
services:
  filerun:
    image: alexphillips/filerun:latest
    network_mode: default
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    depends_on:
      - db
    links:
      - db:db
    environment:
      FR_DB_HOST: 192.168.68.104
      FR_DB_PORT: 33067
      FR_DB_NAME: filerun
      FR_DB_USER: filerun
      FR_DB_PASS: fileruncasaos
    ports:
      - target: 80
        published: "3386"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/filerun/config
        target: /config
      - type: bind
        source: /DATA/AppData/filerun/html
        target: /var/www/html
      - type: bind
        source: /DATA/AppData/filerun/user-file
        target: /user-files
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: fileruncasaos
      MYSQL_DATABASE: filerun
      MYSQL_USER: filerun
      MYSQL_PASSWORD: fileruncasaos
    ports:
      - target: 3306
        published: '33067'
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/filerun/mysql
        target: /var/lib/mysql
        
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: FileRun - Just like you do with an FTP server, point FileRun to where you keep the files on your server, and you will get instant web access to them.
  tagline:
    en_us: FileRun - Just like you do with an FTP server, point FileRun to where you keep the files on your server, and you will get instant web access to them.
  developer: ''
  author: adrianocandrade
  icon: https://raw.githubusercontent.com/adrianocandrade/CasaOS-APPsCloud/master/icons/filerun.png
  thumbnail: https://raw.githubusercontent.com/adrianocandrade/CasaOS-APPsCloud/master/icons/filerun.png
  title:
    en_us: FileRun
  category: Cloud
  port_map: '3386'
