name: filerun
services:
  filerun:
    image: alexphillips/filerun:latest
    network_mode: default
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    ports:
      - target: 80
        published: "3386"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/filerun/config
        target: /config
      - type: bind
        source: /DATA/AppData/filerun/html
        target: /var/www/html
      - type: bind
        source: /DATA/AppData/filerun/user-file
        target: /user-files
        
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: FileRun - Just like you do with an FTP server, point FileRun to where you keep the files on your server, and you will get instant web access to them.
    pt_br: FileRun - Assim como você faz com um servidor FTP, aponte o FileRun para onde você mantém os arquivos em seu servidor e você obterá acesso instantâneo a eles pela Web.
  tagline:
    en_us: FileRun - Just like you do with an FTP server, point FileRun to where you keep the files on your server, and you will get instant web access to them.
    pt_br: FileRun - Assim como você faz com um servidor FTP, aponte o FileRun para onde você mantém os arquivos em seu servidor e você obterá acesso instantâneo a eles pela Web.
  developer: ''
  author: adrianocandrade
  icon: https://raw.githubusercontent.com/adrianocandrade/CasaOS-APPsCloud/master/images/icons/filerun.png
  thumbnail: https://raw.githubusercontent.com/adrianocandrade/CasaOS-APPsCloud/master/images/icons/filerun.png
  project_url: https://github.com/adrianocandrade/CasaOS-APPsCloud
  store_app_id: filerun
  title:
    en_us: FileRun
    pt_br: FileRun
  category: Cloud
  port_map: '3386'
